# no xenial support from travis yet...
dist: trusty
sudo: enabled

# get c++14 compatible gcc version
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5

language: cpp

cache: ccache

matrix:
  include:
  - compiler: gcc
    os: linux
    env: BUILD_TYPE=Release
  - compiler: clang
    os: linux
    env: BUILD_TYPE=Debug
  - compiler: clang
    os: linux
    env: BUILD_TYPE=Release
  - compiler: clang
    os: osx
    env: BUILD_TYPE=Release

env:
  global:
    - MAKEFLAGS="-j 2"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then scripts/ci-install-linux-deps.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then scripts/ci-install-osx-deps.sh ; fi

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - make
#  - make test
